name: FORCE_BUILD
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Обновили до v4

      - name: Build
        run: |
          csc.exe /target:winexe /out:FREE.exe Free.cs
          csc.exe /target:winexe /out:PRO.exe Pro.cs

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # Самое важное: поменяли v3 на v4
        with:
          name: EXECs
          path: "*.exe"
