name: Build_FREE
on: [workflow_dispatch, push]

jobs:
  build_free:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile Free
        # Используем встроенный компилятор напрямую через путь
        run: |
          $cscPath = Get-ChildItem -Recurse -Path "C:\Program Files\Microsoft Visual Studio" -Filter "csc.exe" | Select-Object -First 1 -ExpandProperty FullName
          & $cscPath /target:winexe /out:FREE_VERSION.exe Free.cs
        shell: powershell

      - name: Upload Free
        uses: actions/upload-artifact@v4
        with:
          name: FREE_EXE
          path: FREE_VERSION.exe
