name: Build FREE Version
on: 
  push:
    paths:
      - 'Free.cs' # Собирает только если изменил Free версию
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Compile FREE
        run: csc.exe /target:winexe /out:EXEC_FREE_PC.exe Free.cs
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Exec_Free_Build
          path: EXEC_FREE_PC.exe
