name: Build FREE Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: List Files
        run: dir  # Это заставит систему "увидеть" твои .cs файлы

      - name: Compile FREE EXEC
        # Если файл называется free.cs (с маленькой), исправь тут!
        run: csc.exe /target:winexe /out:EXEC_FREE_PC.exe free.cs

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: Exec_Free_Build
          path: EXEC_FREE_PC.exe
