name: Build FREE Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Check if File Exists
        run: dir # Эта команда покажет список файлов в логах, если упадет

      - name: Compile FREE EXEC
        # Если твой файл называется иначе, поправь Free.cs на правильное имя здесь:
        run: csc.exe /target:winexe /out:EXEC_FREE_PC.exe Free.cs

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: Exec_Free_Version
          path: EXEC_FREE_PC.exe
