name: Build PRO Version
on: 
  push:
    paths:
      - 'Pro.cs' # Собирает только если изменил Pro версию
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Compile PRO
        run: csc.exe /target:winexe /out:EXEC_PRO_PC.exe Pro.cs
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Exec_Pro_Build
          path: EXEC_PRO_PC.exe
