name: Build_PRO
on: [workflow_dispatch, push]

jobs:
  build_pro:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Pro
        run: |
          $csc = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
          & $csc /target:winexe /out:PRO_VERSION.exe Pro.cs
        shell: powershell

      - name: Upload Pro
        uses: actions/upload-artifact@v4
        with:
          name: PRO_EXE
          path: PRO_VERSION.exe
