name: Build PRO Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Compile PRO EXEC
        run: csc.exe /target:winexe /out:EXEC_PRO_PC.exe pro.cs

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: Exec_Pro_Build
          path: EXEC_PRO_PC.exe
